version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip3 install -r requirements.txt -t Layer/python/
  build:
    commands:
      - sam build
      - sam deploy --no-confirm-changeset
